org: bitsofprocess
app: ourlt
service: ourLT
frameworkVersion: '3'
# plugins:
  # - serverless-dynamodb-local
  # - serverless-offline

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  environment:
      dynamoTableName: ${self:custom.dynamoTableName}
  httpApi:
    cors: true
  iam:
    role:
      statements:

        - Effect: Allow
          Action:
              - dynamodb:*
              - s3:*
              - ses:*
          Resource: '*'

custom:
  currentStage: ${opt:stage, self:provider.stage}
  dynamoTableName: ourLT-${self:custom.currentStage}

package:
    individually: true


functions:
  simple:
    handler: SLStest.simple
   
    events:
      - httpApi:
          path: /
          method: post
          cors: true

resources:
  Resources:
    ourLTProd:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.dynamoTableName}
        AttributeDefinitions:
          -
            AttributeName: team_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: team_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST




